# Generated by Django 4.1 on 2022-10-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_staff_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
