# Generated by Django 4.1 on 2022-10-06 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_location_alter_course_prerequisite_courses'),
        ('students', '0003_delete_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='progress',
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.CharField(choices=[('ATTENDED', 'Attended'), ('FAILED INTERVIEW', 'Failed Interview.'), ('PASSED INTERVIEW', 'Passed Interview.'), ('NOT INVITED', 'Not Invited.'), ('REJECTED', 'Rejected'), ('CRITERIA NOT MET', 'Criteria not met.')], max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
        ),
    ]
