# Generated by Django 4.1 on 2022-10-04 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('prerequisite_courses', models.ManyToManyField(blank=True, null=True, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('to_pay', models.IntegerField(default=None)),
                ('already_paid', models.IntegerField(default=None)),
                ('courses', models.ManyToManyField(default=None, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='skills_id',
            field=models.ManyToManyField(default=None, to='courses.skill'),
        ),
        migrations.AddField(
            model_name='course',
            name='supplier_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.supplier'),
        ),
    ]
