# Generated by Django 4.1 on 2022-10-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='id_course',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='courses',
            field=models.ManyToManyField(default=None, null=True, to='courses.course'),
        ),
    ]
