# Generated by Django 4.1 on 2022-10-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(choices=[('GK', 'Greek Campus'), ('OTHER', 'Other')], default='GK', max_length=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='prerequisite_courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
